<?php

// This function automatically makes an image gallery.
// You just need to call it from where you want eg: echo make_gal('path to image folder/','width','height','crop 1 or 0');
// remember to have the folder cache in your root and have the folder permissions to 755
						
function make_gal($images, $width, $height, $crop) {

if ($handle = opendir($images)) {
   while (false !== ($file = readdir($handle))) {
       if ($file != "." && $file != ".." ) {
           $files[] = $file;
       }
   }
   closedir($handle);
}
	$gal = '<ul class="photo_gallery">';
	foreach($files as $file) {
		$gal .=  '<li><a href="'.$images.$file.'" data-rel="prettyPhoto"><img src="php_helpers/timthumb.php?src=../'.$images.$file.'&amp;w='.$width.'&amp;h='.$height.'&amp;zc='.$crop.'" alt=""></a></li>';
	}
	$gal .=  '</ul>'; 
	
	return $gal;
}
?>
<!doctype html>
<!--[if lt IE 7 ]> <html lang="en-gb" class="ie6 oldie no-js"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en-gb" class="ie7 oldie no-js"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en-gb" class="ie8 oldie no-js"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en-gb" class="ie9 no-js"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en-gb" class="no-js"> <!--<![endif]-->

<head>
<title>Photo Gallery | EKHO Template</title>
<?php include ('inc.head.php'); ?>
</head>

<body class="dark header-vertical">
    <?php include('inc.fb-sdk.php'); ?>
        
    <div id="page_wrapper">
    
    	<div id="gradient"></div><!-- gradient background -->
        
        <div id="background"></div><!-- end background -->
        
        <div id="header" class="vertical" data-type="vertical">
			<?php include ('inc.header.php'); ?>
        </div><!-- end header -->
        
        <div id="main" class="container">
            <a href="#" id="mainClose" class="maximized" data-rel="tipsye" title="Minimize"></a>
            <div class="inner-container">
            	
                <div id="breadcrumbs" class="row">
                    <div class="breadcrumb ten columns omega">
                    	<div class="breadcrumbs">
                    		<a href="index.html" class="pathway isHome ">Home</a>
                            <span class="brd_separator">/</span>
                            <span>FEATURES</span>
                            <span class="brd_separator">/</span>
                            <span>PHOTO GALLERY</span>
                        </div>
                    </div><!-- end breadcrumbs -->
                    <div class="thedate six columns alpha">
                    	<span id="current-date"></span>
                    </div>
                    <div class="clear"></div>
                </div><!-- end breadcrumbs -->
                                    
                <div class="row">
                
                    <div class="sixteen noSidebars columns">
                        <div id="mainbody">
                            <div class="item-page ">
                                <h2>PHOTO GALLERY</h2>
                                
                                <h2>First gallery (dinamically created with php - only for images)</h2>
                                <p>This gallery it's generated by php, reading all (and only) the images within a certain folder you define.</p>
                                <?php
                                // make_gal('path to image folder/','width','height','crop 1 or 0');
                                
                                echo make_gal('images/gallery/first/','155','115','0');
                                ?>
                                
                                <h2>Second gallery - contains both photos and videos</h2>
                                <p>This gallery is manually created with simple html tags, but with some php helpers like timthumb (for creating thumbnails) and player.php to add iframe'd flv videos</p>
                                
                                <!-- The "addcaption" class is a trigger to captionize the thumbnails -->
                                <ul class="photo_gallery addcaption">
                                    <!-- to add a photo icon, add the class "photo" -->
                                    <!-- as you can see the image's src are added with the help of timthumb.php to create the thumbnails -->
                                    <li><a data-rel="prettyPhoto" href="images/gallery/second/1336635_63765576.jpg" title="Simple Image">
                                        <img alt="" src="php_helpers/timthumb.php?src=../images/gallery/second/1336635_63765576.jpg&amp;w=155&amp;h=115&amp;zc=0"></a></li>
                                        
                                    <!-- to add a video icon, add the class "video" -->
                                    <li><a data-rel="prettyPhoto[flash]" href="images/flv/sample.swf?width=620&amp;height=375" title="Flash Media">
                                        <img alt="" src="php_helpers/timthumb.php?src=../images/gallery/second/1336342_22583242.jpg&amp;w=155&amp;h=115&amp;zc=0"></a></li>
                                    
                                    <li><a data-rel="prettyPhoto[iframes]" href="php_helpers/player.php?video=../images/flv/animation.flv&amp;iframe=true&amp;width=620&amp;height=375" title="FLV Video">
                                        <img alt="" src="php_helpers/timthumb.php?src=../images/gallery/second/1336882_90276791.jpg&amp;w=155&amp;h=115&amp;zc=0"></a></li>
                                    
                                    <li><a data-rel="prettyPhoto" href="http://www.youtube.com/watch?v=OHUpQZIylVc" title="YouTube Video">
                                        <img alt="" src="php_helpers/timthumb.php?src=../images/gallery/second/1336633_65751997.jpg&amp;w=155&amp;h=115&amp;zc=0"></a></li>
                                        
                                    <li><a data-rel="prettyPhoto" href="http://vimeo.com/5233789" title="Vimeo Video">
                                        <img alt="" src="php_helpers/timthumb.php?src=../images/gallery/second/1336338_84064705.jpg&amp;w=155&amp;h=115&amp;zc=0"></a></li>
                                </ul>
                                
                            </div><!-- end item-page-->
                        </div><!-- end mainbody -->
                    </div>
                
                </div><!-- end row -->
            </div>
        </div><!-- end main -->
        <div class="footerFix"></div><!-- FooterFix (needed for properly rendering the #main div) -->
        
        
		<!-- social sharing -->
        <?php include ('inc.social_sharing.php'); ?>
        
        <!-- footer -->
        <?php include ('inc.footer.php'); ?>
        
        <!-- live comments panel -->
        <?php include ('inc.live_comments.php'); ?>
        
        
    </div><!-- end page_wrapper -->
	
    <!-- Start Backstretch full-background code -->
    <script type = "text/javascript" src="js/jquery.backstretch.min.js"></script>
	<script type="text/javascript">
    (function($){
		// trigger the Fullscreen background
        $.backstretch("images/bg1.jpg");
    })(jQuery);
	</script><!-- End Backstretch full-background code -->
	
    <!-- Load JS Files -->
	<?php include ('inc.js.php'); ?>	
	
</body>
</html>